DECLARE @fecha_inicio_venta DATE = ?;
DECLARE @fecha_fin_venta DATE = ?;
DECLARE @fecha_inicio_stock DATE = ?;
DECLARE @ini_cliente VARCHAR(10) = ?;
DECLARE @stock_threshold INT = ?; -- Parametro umbral stock


;WITH Valid_Marca_Tipo AS (
    SELECT
        CASE
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090103' THEN 'YAMP B'
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090303' THEN 'YAMP G'
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090504' THEN 'YAMP BEBA'
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090503' THEN 'YAMP BEBO'
            ELSE ISNULL(MA.NEW_MARCA, EC.MARCA )
        END AS 'Marca',
        M.TIPO AS 'Tipo_Programa',
        M.FIT AS 'Fit_Estilo'
    FROM [DWH_INCO].[dbo].DWH_Stock AS ST
    LEFT JOIN [DWH_INCO].[dbo].[CAT_SKU] AS EC ON ST.EAN = EC.EAN
    LEFT JOIN [DWH_INCO].[dbo].[MONITOREO] AS M ON EC.REF_MODELO = M.MODELO and  EC.MARCA = M.MARCA
    LEFT JOIN [DWH_INCO].[dbo].MARCA AS MA ON EC.MARCA = MA.MARCA_BD
    LEFT JOIN [DWH_INCO].[dbo].TIENDAS AS T ON ST.NUM_LOCAL = T.CODIGO
    WHERE ST.INI_CLIENTE = @ini_cliente
      AND T.TIPO = 'TIENDA'
      AND ST.FECHA = @fecha_fin_venta
    GROUP BY
        CASE
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090103' THEN 'YAMP B'
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090303' THEN 'YAMP G'
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090504' THEN 'YAMP BEBA'
            WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090503' THEN 'YAMP BEBO'
            ELSE ISNULL(MA.NEW_MARCA, EC.MARCA )
        END,
        M.TIPO,
        M.FIT
    HAVING SUM(ST.CANT) >= @stock_threshold
)

Select
syv.INI_CLIENTE AS 'Ini_Cliente'
,syv.C_L
,syv.[LOCAL] AS 'Local'
,syv.Ciudad
,syv.L_Tipo
,syv.CURVA as 'Curva'
,syv.EAN
,syv.SKU
,syv.[Desc Agrupacion]
,syv.Modelo
,syv.Marca
,syv.Subclase
,syv.Tipo_Programa
,syv.FIT as 'Fit_Estilo'
,syv.COD_COLOR as 'C_Color'
,syv.COLOR_XXXX
,syv.COLOR
,syv.Color_Hexa
,syv.TIPO_COLOR
,syv.Talla as 'Talla'
,syv.Fecha
,CONCAT(FORMAT(syv.fecha,'yy'),'/',FORMAT(syv.N_sem,'00'),' - ',FORMAT(syv.Fecha, 'MM/dd')) as 'Semanas'
,syv.N_Sem
,syv.Ano
,SUM(syv.CANT) as 'Cant_Venta'
,SUM(syv.STOCK) as 'Cant_Stock'
,'PVP_Prom' = CASE WHEN SUM(syv.CANT) = 0 THEN NULL ELSE ROUND(SUM(syv.CANT * syv.PVP_UNIT)/ SUM(syv.CANT),0) END

From(

SELECT
-- BASE DE DATOS STOCK
ST.INI_CLIENTE
,ST.NUM_LOCAL AS 'C_L'
,T.LOCAL AS 'Local'
,T.CIUDAD AS 'Ciudad'
,T.TIPO AS 'L_Tipo'
,T.CURVA
,ST.EAN
,EC.SKU
,EC.MODELO_AGRUPACION AS 'Desc Agrupacion'
,EC.REF_MODELO AS 'Modelo'
,CASE 
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090103' THEN 'YAMP B'
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090303' THEN 'YAMP G'
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090504' THEN 'YAMP BEBA'
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090503' THEN 'YAMP BEBO'
ELSE ISNULL(MA.NEW_MARCA, EC.MARCA )
END  AS 'Marca'
,SUBSTRING(EC.CATEGORIA,1,7) AS 'Subclase'
,M.TIPO AS 'Tipo_Programa'
,M.FIT
,EC.COD_COLOR 
,CO.COLOR_XXXX
,CO.COLOR
,CO.Color_Hexa
,CO.TIPO_COLOR
,EC.TALLA 
,DATEADD(day,1 -DATEPART(WEEKDAY,ST.FECHA),CAST(ST.FECHA as date)) AS 'Fecha'
,SEM.N_SEM as 'N_Sem'
,SEM.ANO as 'Ano'
,NULL AS CANT
,ST.CANT AS 'STOCK'
,NULL AS 'PVP_UNIT'
 
FROM [DWH_INCO].[dbo].DWH_Stock AS ST

LEFT JOIN [DWH_INCO].[dbo].[CAT_SKU] AS EC ON ST.EAN = EC.EAN
LEFT JOIN [DWH_INCO].[dbo].[MONITOREO] AS M ON EC.REF_MODELO = M.MODELO and  EC.MARCA = M.MARCA
LEFT JOIN [DWH_INCO].[dbo].[COD_COLOR] as CO on EC.COD_COLOR = CO.CODIGO
LEFT JOIN [DWH_INCO].[dbo].TIENDAS AS T ON ST.NUM_LOCAL = T.CODIGO
LEFT JOIN [DWH_INCO].[dbo].MARCA AS MA ON EC.MARCA = MA.MARCA_BD
LEFT JOIN [DWH_INCO].[dbo].SEMANAS AS SEM ON DATEADD(day,1 -DATEPART(WEEKDAY,ST.FECHA),CAST(ST.FECHA as date)) = SEM.DIA_INICIO
INNER JOIN Valid_Marca_Tipo VMT ON VMT.Marca = (
    CASE 
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090103' THEN 'YAMP B'
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090303' THEN 'YAMP G'
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090504' THEN 'YAMP BEBA'
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090503' THEN 'YAMP BEBO'
        ELSE ISNULL(MA.NEW_MARCA, EC.MARCA )
    END 
) AND VMT.Tipo_Programa = M.TIPO AND ISNULL(VMT.Fit_Estilo,'') = ISNULL(M.FIT,'')

WHERE ST.INI_CLIENTE = @ini_cliente and T.TIPO = 'TIENDA' 
and st.FECHA between @fecha_inicio_stock and @fecha_fin_venta

UNION all

SELECT
-- BASE DE DATOS VENTAS
VT.INI_CLIENTE
,VT.NUM_LOCAL AS 'C_L'
,T.LOCAL AS 'Local'
,T.CIUDAD AS 'Ciudad'
,T.TIPO AS 'L_Tipo'
,T.CURVA
,VT.EAN
,EC.SKU
,EC.MODELO_AGRUPACION AS 'Desc Agrupacion'
,EC.REF_MODELO AS 'Modelo'
,CASE 
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090103' THEN 'YAMP B'
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090303' THEN 'YAMP G'
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090504' THEN 'YAMP BEBA'
WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090503' THEN 'YAMP BEBO'
ELSE ISNULL(MA.NEW_MARCA, EC.MARCA )
END  AS 'Marca'

,SUBSTRING(EC.CATEGORIA,1,7) AS 'Subclase'
,M.TIPO AS 'Tipo_Programa'
,M.FIT
,EC.COD_COLOR 
,CO.COLOR_XXXX
,CO.COLOR
,CO.Color_Hexa
,CO.TIPO_COLOR
,EC.TALLA
,DATEADD(day,1 -DATEPART(WEEKDAY,VT.FECHA),CAST(VT.FECHA as date)) AS 'Fecha'
,SEM.N_SEM
,SEM.ANO
,VT.CANT as CANT
,0 AS STOCK
,NULLIF(VT.PVP_UNIT,0) as 'PVP_UNIT'
 
FROM [DWH_INCO].[dbo].[DWH_Ventas] VT

LEFT JOIN [DWH_INCO].[dbo].[CAT_SKU] AS EC ON VT.EAN = EC.EAN
LEFT JOIN [DWH_INCO].[dbo].[COD_COLOR] as CO on EC.COD_COLOR = CO.CODIGO
LEFT JOIN [DWH_INCO].[dbo].[MONITOREO] AS M ON EC.REF_MODELO = M.MODELO and  EC.MARCA = M.MARCA
LEFT JOIN [DWH_INCO].[dbo].TIENDAS AS T ON VT.NUM_LOCAL = T.CODIGO
LEFT JOIN [DWH_INCO].[dbo].MARCA AS MA ON EC.MARCA = MA.MARCA_BD
LEFT JOIN [DWH_INCO].[dbo].SEMANAS AS SEM ON DATEADD(day,1 -DATEPART(WEEKDAY,VT.FECHA),CAST(VT.FECHA as date)) = SEM.DIA_INICIO
INNER JOIN Valid_Marca_Tipo VMT ON VMT.Marca = (
    CASE 
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090103' THEN 'YAMP B'
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090303' THEN 'YAMP G'
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090504' THEN 'YAMP BEBA'
        WHEN SUBSTRING(EC.CATEGORIA,1,7) = 'J090503' THEN 'YAMP BEBO'
        ELSE ISNULL(MA.NEW_MARCA, EC.MARCA )
    END 
) AND VMT.Tipo_Programa = M.TIPO AND ISNULL(VMT.Fit_Estilo,'') = ISNULL(M.FIT,'')

WHERE VT.INI_CLIENTE = @ini_cliente and T.TIPO = 'TIENDA' 
and VT.FECHA between @fecha_inicio_venta and @fecha_fin_venta
--Where VT.INI_CLIENTE = 'FL' and VT.FECHA between '20230901' and '20240730'

) as syv

GROUP BY
syv.INI_CLIENTE
,syv.C_L
,syv.[LOCAL]
,syv.Ciudad
,syv.L_Tipo
,syv.CURVA
,syv.EAN
,syv.SKU
,syv.[Desc Agrupacion]
,syv.Modelo
,syv.Marca
,syv.Subclase
,syv.Tipo_Programa
,syv.FIT
,syv.COD_COLOR
,syv.COLOR_XXXX
,syv.COLOR
,syv.Color_Hexa
,syv.TIPO_COLOR
,syv.TALLA
,syv.Fecha
,CONCAT(FORMAT(syv.fecha,'yy'),'/',FORMAT(syv.N_sem,'00'),' - ',FORMAT(syv.Fecha, 'MM/dd'))
,syv.N_SEM
,syv.ANO
